
version: '3.8'

services:
  camunda-worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ZEEBE_ADDRESS=141.26.157.251:8081
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    networks:
      - camunda-network

networks:
  camunda-network:
    driver: bridge